### ISSUE TITLE
ng-manger pod is crashing in every 15 minutes.

### ISSUE THREAD

**Issue by abhi-dev91** [harness/harness-cd-community#75] opened 2023-03-20 12:09 UTC
**Describe the bug**

When I deployed the harness CD community helm chart on minikube instance, the ng-manger pod inside it is continuosly crashing after every 10-15 minutes, With the following error.

```2023-03-19 09:45:05,357 [FreezeTemplateRegistrationService-0] WARN  io.harness.remote.client.NGRestUtils - Request failed. Attempt : 1.
java.net.ConnectException: Failed to connect to localhost/127.0.0.1:9005
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at io.harness.remote.client.AbstractHttpClientFactory.lambda$getUnsafeOkHttpClient$0(AbstractHttpClientFactory.java:235)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at io.harness.request.RequestContextFilter.lambda$getRequestContextInterceptor$0(RequestContextFilter.java:96)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at io.harness.remote.client.AbstractHttpClientFactory.lambda$getGitContextInterceptor$1(AbstractHttpClientFactory.java:265)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at io.harness.ng.core.CorrelationContext.lambda$getCorrelationIdInterceptor$0(CorrelationContext.java:50)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at io.harness.remote.client.AbstractHttpClientFactory.lambda$getAuthorizationInterceptor$2(AbstractHttpClientFactory.java:290)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
        at io.harness.remote.client.NGRestUtils.executeRequest(NGRestUtils.java:65)
        at io.harness.remote.client.NGRestUtils.lambda$getResponse$0(NGRestUtils.java:45)
        at net.jodah.failsafe.Functions.lambda$resultSupplierOf$11(Functions.java:284)
        at net.jodah.failsafe.RetryPolicyExecutor.lambda$supply$0(RetryPolicyExecutor.java:63)
        at net.jodah.failsafe.Execution.executeSync(Execution.java:129)
        at net.jodah.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:379)
        at net.jodah.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:70)
        at io.harness.remote.client.NGRestUtils.getResponse(NGRestUtils.java:45)
        at io.harness.notification.notificationclient.NotificationClientImpl.saveNotificationTemplate(NotificationClientImpl.java:85)
        at io.harness.freeze.FreezeNotificationTemplateRegistrar.run(FreezeNotificationTemplateRegistrar.java:44)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        ... 41 common frames omitted```

**To Reproduce**
Steps to reproduce the behavior:
1. Setup a minikube instance on ubuntu using the following script - https://github.com/abhi-dev91/minikube-ubuntu-setup.git
2. Clone the harness cd repository and install it using helm

**Comment by sean-harness** [comment] 2023-03-20 12:21
Can you try increasing the memory for the platform service in the values.yaml file?
```
platform:
  config:
    memory: 500
  resources:
    limits:
      memory: 600Mi
      cpu: 1
    requests:
      memory: 600Mi
      cpu: 200m
```

**Comment by harnesspravin** [comment] 2023-03-27 04:41
Please check PR https://github.com/harness/harness-cd-community/pull/76/files for new memory values and try it. Let us know the result.

**Comment by harnesspravin** [comment] 2023-04-29 17:00
The issue is resolved in the newly released version:  https://github.com/harness/harness-cd-community/releases/tag/789xx

**Closed by harnesspravin** 2023-04-29 17:00 UTC
