### ISSUE TITLE
Pipeline not getting deployed

### ISSUE THREAD

**Issue by amanpreet9999** [harness/harness-cd-community#73] opened 2023-03-17 03:46 UTC
**Describe the bug**
Hello Team,
I am closely trying to follow this official documentation of [Harness](https://developer.harness.io/docs/continuous-delivery/onboard-cd/cd-quickstarts/harness-community-edition-quickstart/) Community Edition Deployment and after following each and every step identically When i try to [Run](https://developer.harness.io/docs/continuous-delivery/onboard-cd/cd-quickstarts/harness-community-edition-quickstart/#step-3-deploy) it, it just keeps on loading, without any change happening , when I checked the developer console , there was just one fetch request happening continuously and pipeline was not getting updated at all and finally after sometime the ng-manager becomes unhealthy and all of the setup stops :(, This is the point where I am stuck since so long now, Can anyone please help me out here ?

**To Reproduce**
Follow [this ](https://developer.harness.io/docs/continuous-delivery/onboard-cd/cd-quickstarts/harness-community-edition-quickstart/#step-3-deploy)documentation until step 3 .

**Expected behavior**
The changes in the pipeline should be deployed and should be visible in the UI.

**Screenshots**

**Installation Method**
- [x] Docker Compose
- [ ] Helm

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 111.0.5563.65 (Official Build) (64-bit)

**Additional context**

**Comment by amanpreet9999** [comment] 2023-03-17 05:46
![Screenshot (9)](https://user-images.githubusercontent.com/65528964/225822756-a5cbc618-d436-4b35-a110-2f31dd908205.png)
![Screenshot (12)](https://user-images.githubusercontent.com/65528964/225822768-4d23b2b0-987f-4d62-b555-04bf708f0596.png)
![Screenshot (11)](https://user-images.githubusercontent.com/65528964/225822772-160ddebd-95f5-47fd-b86e-137541c63b39.png)

**Comment by amanpreet9999** [comment] 2023-03-17 05:51
After 7 minutes :- 
![Screenshot (14)](https://user-images.githubusercontent.com/65528964/225823478-dce5a710-29db-4496-89ad-cc303094feb3.png)
![Screenshot (13)](https://user-images.githubusercontent.com/65528964/225823490-183001f1-214a-4d8a-a218-578d8f12e6e2.png)

**Comment by amanpreet9999** [comment] 2023-03-17 06:15
it's been 32 minutes and still no changes can be seen in the pipeline
![Screenshot (15)](https://user-images.githubusercontent.com/65528964/225827223-c485767f-e086-4549-afdd-90d656aab0b5.png)

**Comment by geekman80** [comment] 2023-03-20 06:41
To be honest, I am also facing the same issues. I tried it number of times but still things are same

**Comment by harnesspravin** [comment] 2023-03-27 04:45
Hi, We have debugged the issue and found that the ng-manager restarted due to a reached memory limit. Please check PR https://github.com/harness/harness-cd-community/pull/76/files for new values and try it. Let us know the result.

**Comment by harnesspravin** [comment] 2023-04-29 17:03
The issue is resolved in the newly released version: https://github.com/harness/harness-cd-community/releases/tag/789xx

**Closed** 2023-04-29 17:04 UTC
