### ISSUE TITLE
Unable to get harness up and running on Apple M1 Pro

### ISSUE THREAD

**Issue by sundaven** [harness/harness-cd-community#79] opened 2023-04-30 19:11 UTC
**Describe the bug**
I am trying to setup Harness thru docker-compose on my mac.   Got the latest release from here. https://github.com/harness/harness-cd-community/releases/tag/789xx.  Post pulling the images, the mongoDB instance if failing to start and getting the following error.
2023-04-30 18:08:12 mongodb 12:38:11.99
2023-04-30 18:08:12 mongodb 12:38:12.02 Welcome to the Bitnami mongodb container
2023-04-30 18:08:12 mongodb 12:38:12.04 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-04-30 18:08:12 mongodb 12:38:12.06 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-04-30 18:08:12 mongodb 12:38:12.09
2023-04-30 18:08:12 /opt/bitnami/scripts/mongodb/entrypoint.sh: line 26: exec: --: invalid option
2023-04-30 18:08:12 exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
Due to the above issue, 4 docker-compose ps are showing unhealthy .   The mongo DB instance is shown as stopped

**To Reproduce**
on Mac M1 Pro, download the code from here. https://github.com/harness/harness-cd-community/releases/tag/789xx.

Follow the documentation given on GitHub harness setup thru docker compose.

**Expected behavior**
MongoDB instance won't start.  

**Screenshots**

**Installation Method**
 Docker Compose

**Environment (please complete the following information):**
 - OS: Mac OS ventura 13.3.1

**Additional context**

Let me know If any additional details needed.  thx.

**Comment by jamezrin** [comment] 2023-05-09 17:43
I encountered a similar issue when I deployed this on a k8s cluster running on arm64 nodes. It seems arm is not supported yet

**Comment by mmonti** [comment] 2023-05-17 19:53
Having the same issue when trying to run it locally. It seems the problem is with the harness/mongo:4.2.19 entrypoint?
Does this image includes any specifics for harness? or I can bring my own mongo instance?
Thanks!

**Comment by mmonti** [comment] 2023-05-17 21:53
I was able to overcome this issue commenting out the command line in the mongo service (from the docker compose) and passing the flags using env. vars.

```yaml
  mongo:
    image: harness/mongo:4.4.19
    deploy:
      resources:
        limits:
          memory: 320m
    # command: --wiredTigerCacheSizeGB 0.125 -f /etc/mongod.conf
    environment:
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=0.125
    healthcheck:
      test: "mongo --eval 'db.runCommand(\"ping\").ok' --quiet"
    networks:
      harness-network:
    volumes:
      - mongo_data:/data/db
      - ./config/mongo/mongod.conf:/etc/mongod.conf
```

With this change, the service starts up.

**Comment by harnesspravin** [comment] 2023-05-18 14:36
Docker Desktop for Mac supports both Apple Silicon(M1) & Intel Chip Docker Containers. In case you are working with Apple Silicon Chip, the official docker docs suggest to [install rosetta](https://docs.docker.com/desktop/install/mac-install/#mac-with-apple-silicon). It will pull all the images successfully.

Right now the issue is with Mongo DB, As mentioned by @mmonti workaround is to comment out line [#189](https://github.com/harness/harness-cd-community/blob/main/docker-compose/harness/docker-compose.yml#L189) from docker-compose.yaml file. After that CD community will be install successfully. 

Regarding the MongoDB issue, we are currently checking on this and will let you know about it.

**Comment by josh383451** [comment] 2023-06-05 11:25
Just to add to this - line #149 in profile-production.yml also needs commenting out if using the Production profile

**Comment by ravilach** [comment] 2023-12-20 18:55
Repo is deprecated. Will close.

**Closed by ravilach** 2023-12-20 18:55 UTC
