### ISSUE TITLE
CrashLoopBackOff error in Harness CD installation using Helm 

### ISSUE THREAD

**Issue by vyadav5** [harness/harness-cd-community#72] opened 2023-03-16 19:00 UTC
I am facing an error while signing up for the harness CD. When I am trying to register with signup information it is showing a gateway error. I tried to troubleshoot it multiple times but one of the pods is showing CrashLoopBackOff and sometimes it shows OOmkilled. I tried to debug it as well but haven't got any way to solve this issue. Attached is the screenshot of my pods with the issue that I have addressed.

Expected behavior: All the pods should run without any error.

**Screenshots**
<img width="839" alt="screenshot" src="https://user-images.githubusercontent.com/79339896/225725762-0322697d-fc14-41be-a135-9b17d3fddf8c.png">

**Installation Method**
- [ ] Helm

**Environment **
 - OS: MacOS Monterey Version 12.2.1
 - google chrome

**Comment by harnesspravin** [comment] 2023-03-18 17:14
@vyadav5  I can see the OOMkilled Status, I would suggest, Start minikube with more resources and see if you still see the issue.

$ minikube start --memory 6g --cpus 4

**Comment by vyadav5** [comment] 2023-03-19 07:56
Hi @harnesspravin , thanks for responding. I tried deleting the minikube cluster and restarted it again with a different memory. I am still getting one crashloopbackoff with my other pods behaving differently.
<img width="855" alt="Screenshot 2023-03-19 at 1 22 19 PM" src="https://user-images.githubusercontent.com/79339896/226161620-2f817eb8-da64-4e02-96f7-4a319e7aceea.png">

**Comment by sean-harness** [comment] 2023-03-20 11:19
Can you try increasing the memory for the platform service in the values.yaml file?
```
platform:
  config:
    memory: 500
  resources:
    limits:
      memory: 600Mi
      cpu: 1
    requests:
      memory: 600Mi
      cpu: 200m
```

**Comment by harnesspravin** [comment] 2023-03-27 04:45
Please check PR https://github.com/harness/harness-cd-community/pull/76/files for new values and try it. Let us know the result.

**Comment by harnesspravin** [comment] 2023-04-29 17:04
The issue is resolved in the newly released version: https://github.com/harness/harness-cd-community/releases/tag/789xx

**Closed by harnesspravin** 2023-04-29 17:04 UTC
